### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by gaearon** [appsforartists/ambidex-example--bike-index#1]
```
TypeError: undefined is not a function
    at http://192.168.2.107:8081/bundles/jsx.js:21513:16
    at Array.forEach (native)
    at camelizeKeys (http://192.168.2.107:8081/bundles/jsx.js:21497:22)
    at Function.BikeModel.fromBikeIndex (http://192.168.2.107:8081/bundles/jsx.js:21531:17)
```

I think it says `endsWith` is undefined—is there a polyfill missing?
This seems to work in Canary but not in stable Chrome.

**Comment by appsforartists** [comment]
For some reason, I'm not getting issue notifications.  Sorry for the delayed reply.

It's quite possible that there's a polyfill missing.  I'll have to remember to add one next week.

Thanks for the report!
