### ISSUE TITLE
getting Type errors when running the example

### ISSUE THREAD

**Issue by amitport** [appsforartists/ambidex-example--bike-index#6]
```
Uncaught TypeError: object is not a function
styles.js:1584 8
styles.js:509 __webpack_require__
styles.js:77 fnstyles.js:6815 94
styles.js:509 __webpack_require__
styles.js:77 fn
styles.js:10776 (anonymous function)
styles.js:10842 98
styles.js:509 __webpack_require__
styles.js:77 fn
styles.js:563 0
styles.js:509 __webpack_require__
styles.js:532 modules.(anonymous function)
styles.js:535 (anonymous function)

Uncaught TypeError: object is not a function
jsx.js:1575 (anonymous function)
jsx.js:509 __webpack_require__
jsx.js:77 fn
jsx.js:40063 (anonymous function)
jsx.js:509 __webpack_require__
jsx.js:77 fn
jsx.js:561 module.exports.module.deprecate
jsx.js:509 __webpack_require__
jsx.js:532 modules.(anonymous function)
jsx.js:535 (anonymous function)
```

(the site does not load correctly)

**Comment by appsforartists** [comment]
Sorry, that doesn't give me enough to help you.  Have you checked to see what's on styles.js:1584 or jsx.js:1575?

Do you have any errors in your terminal?  I'm investigating a report (#7) of Webpack misbehaving when the name is lowercase.  Perhaps these issues are related.

Please share what you see when you go here:

http://bikeindex.local:8081/bundles/jsx.js

**Comment by appsforartists** [comment]
@amitport Does upgrading to `ambidex@0.1.1` resolve your issue?

**Comment by amitport** [comment]
Hey just got around to re-try this... 

Sorry, I can't reproduce this issue with ambidex@0.1.1, because in the meantime I upgraded to node@0.12 which caused node-sass@0.9.6 (used by ambidex->sass-loader) to fail to install (node-sass@0.9.6 does not support node@0.12)

**Comment by appsforartists** [comment]
This is a big motivator to stop including SASS by default in v0.2.0:

https://github.com/appsforartists/ambidex/tree/iojs
